services:
  nginx:
    build: nginx
    image: node-discord-hook-nginx:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 32M
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ${APP_FILES_STATIC:-./app/static}:/data/static

  app:
    build: app
    image: node-discord-hook-app:latest
    command: "npx nodemon app.js"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 64M
    volumes:
      - ${APP_FILES:-./app}:/app
