FROM nginx:mainline

LABEL org.opencontainers.image.source="https://github.com/smashedr/node-discord-hook"
LABEL org.opencontainers.image.description="NodeJS Discord Webhook"
LABEL org.opencontainers.image.authors="smashedr"

ENV TZ=UTC

COPY nginx.conf /etc/nginx/nginx.conf
