name: "Build"

on:
  workflow_dispatch:
  release:
    types:
      - published
  push:
    branches:
      - master
    paths:
      - "app/**"
      - "nginx/**"
      - "docker-compose-build.yaml"
  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      #      - name: "Docker Login"
      #        uses: docker/login-action@v2
      #        with:
      #          registry: ghcr.io
      #          username: ${{ vars.GHCR_USER }}
      #          password: ${{ secrets.GHCR_PASS }}
      #
      #      - name: "Setup Buildx"
      #        uses: docker/setup-buildx-action@v2
      #        with:
      #          platforms: linux/amd64,linux/arm64
      #
      #      - name: "Bake and Push"
      #        uses: docker/bake-action@v5
      #        with:
      #          files: docker-compose-build.yaml
      #          push: true

      - name: "Portainer Deploy"
        uses: cssnr/portainer-stack-deploy-action@master
        with:
          url: https://portainer.cssnr.com/
          token: ${{ secrets.PORTAINER_TOKEN }}
          file: docker-compose-swarm.yaml
          name: node-discord-hook
