name: "Build"

on:
  pull_request:
    branches: ["master"]
  release:
    types: ["published"]
  workflow_dispatch:
  repository_dispatch:
    types: ["webhook"]
#  push:
#    branches: ["master"]
#    tags: ["*"]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Docker Login"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: "Bake and Push"
        uses: docker/bake-action@v5
        with:
          files: docker-bake.hcl
          push: true
